### PR TITLE
Add "Zap In" button to main landing page

### PR DESCRIPTION
**Pull request by z80dev**
I initially tried to use the same round zap icon from the cemetary page, but had issues getting it all lined up right. Maybe "Zap in" is still a good idea, since there aren't the two "+" and "-" buttons surrounding the zap function like on the cemetary page.

### CODE REVIEW

**Comment by z80dev** [comment]
Screen Shot 2021-06-21 at 8 09 14 PM

**Comment by thecryptoundertaker** [comment]
Would it be possible to align the button to be in the center? Currently it's slightly moved to the left in comparison with the LP icons.

**Comment by z80dev** [comment]
Updated to remove the margins, here's a new screenshot

Screen Shot 2021-06-22 at 10 02 24 AM

**Review by thecryptoundertaker — APPROVED** [review]
Reviewed and tested. Ready to be merged.

**Pull request merged**
